---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    foo: bar
spec:
  containers:
    - name: alpine
      image: alpine
      command: ['sh', '-c', 'echo the value of FOO is $FOO']
      env:
        - name: FOO
          value: BAR